### ISSUE TITLE
Failing extractor

### ISSUE THREAD

**Issue by JakubMatejka** [pocin/kbc-mailchimp-writer#7]
We get this error from the app:
```
INFO:root:Validating credentials
INFO:root:Credentials OK
'str' object does not support item assignment
Traceback (most recent call last):
  File \"\/src\/mcwriter\/writer.py\", line 348, in run
    run_writer(client, params, tables, datadir=datadir)
  File \"\/src\/mcwriter\/writer.py\", line 405, in run_writer
    created_lists = create_lists(client, csv_lists=path_new_lists)
  File \"\/src\/mcwriter\/writer.py\", line 110, in create_lists
    serialized_data = serialize_lists_input(csv_lists)
  File \"\/src\/mcwriter\/utils.py\", line 59, in serialize_lists_input
    serialized_line = serialize_dotted_path_dict(cleaned_flat_data)
  File \"\/src\/mcwriter\/utils.py\", line 40, in serialize_dotted_path_dict
    serialized[lvl1][lvl2] = value
TypeError: 'str' object does not support item assignment
```
Happens here: https://github.com/pocin/kbc-mailchimp-writer/blob/master/mcwriter/utils.py#L40
Would you have any idea what's wrong?

**Comment by pocin** [comment]
Can you send me the config.json + header (or anonymized few top rows) of the input csv?

**Comment by JakubMatejka** [comment]
Configuration is:
```
{
    "storage": {
      "input": {
        "tables": [
          {
            "source": "out.c-datasentics-analytika.new_lists",
            "destination": "new_lists.csv",
            "where_column": "",
            "where_values": [],
            "where_operator": "eq",
            "columns": []
          }
        ]
      }
    },
    "parameters": {
      "#apikey": "..."
    }
  }
```
And here is an overview of table columns (it has only one row):
![2018-05-01 15-50-34](https://user-images.githubusercontent.com/215660/39475209-acfbcfb2-4d57-11e8-8595-ad75e0e30461.png)
The columns seem to be little bit different from the template (https://github.com/pocin/kbc-mailchimp-writer/blob/master/templates/new_lists/new_lists.csv) but I don't know if it is the problem.

**Comment by pocin** [comment]
can you export the table from storage, anonymize and paste it here as a code? I need the header (literally character for character).

**Comment by JakubMatejka** [comment]
Oh right, I am sorry, here is the file.
[out.c_datasentics_analytika.new_lists.csv.txt](https://github.com/pocin/kbc-mailchimp-writer/files/1964561/out.c_datasentics_analytika.new_lists.csv.txt)

**Comment by pocin** [comment]
Alright, the issue is the column `campaign_defaults: "nevim co sem"`. 
In the [actual JSON](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/#create-post_lists) which is sent to api, the `campaign_defaults` value is an object, here you are saying you want a string there.

all the fields `campaign_defaults__<from_name>` are valid, the `campaign_defaults` itself is not.

I will work on a fix to improve the error messages, in the meantime, just delete the `campaign_defaults` column.

The same applies to the `contact` column 

this should be serializable (deleted the columns `contact` and `campaign_defaults`)

```
"list_id","email_address","email_type_option","name","contact","permission_reminder","contact__company","contact__address1","contact__city","contact__state","contact__zip","contact__country","campaign_defaults__from_name","campaign_defaults__from_email","campaign_defaults__subject","campaign_defaults__language","visibility"
"tst","foo@example.com","FALSE","Testovaci publikum","...","Dostali jste tento mail, protože jste našim zákazníkem.","...","...","Prague","","104 00","CZ","...","...","Kupte si 70","cs","pub"
```

the csv
```
email,contact__city
foo@example.com,Prague
```
will be serialized into
```
{
  "email": "foo@example.com", 
  "contact": {"city": "Prague"}
}
```
if you write
```
email,contact__city,contact
foo@example.com,Prague,whatever
```
there is a clash

```
{
  "email": "foo@example.com", 
  "contact": {"city": "Prague"}  # or "contact": "whatever" ???
}
```
Does that make sense or should I elaborate more?

**Comment by jakubstech** [comment]
Thank you very much for the explanation, it was helpful :)
