### ISSUE TITLE
JSONDecodeError raised for _add_members_in_batch 

### ISSUE THREAD

**Issue by kacurez** [pocin/kbc-mailchimp-writer#9]
Not sure if it is enough info to be able to debug what happened but here is what we got:
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
<details>
<summary>
full stack trace
</summary>
<pre>
INFO:root:Batch job request sent {'id': '9658d3d2bd', 'status': 'pending', 'total_operations': 0, 'finished_operations': 0, 'errored_operations': 0, 'submitted_at': '2019-02-06T06:32:40+00:00', 'completed_at': '', 'response_body_url': '', '_links': [{'rel': 'parent', 'href': 'https://us12.api.mailchimp.com/3.0/batches', 'method': 'GET', 'targetSchema': 'https://us12.api.mailchimp.com/schema/3.0/Definitions/Batches/CollectionResponse.json', 'schema': 'https://us12.api.mailchimp.com/schema/3.0/CollectionLinks/Batches.json'}, {'rel': 'self', 'href': 'https://us12.api.mailchimp.com/3.0/batches/9658d3d2bd" target="_blank">https://us12.api.mailchimp.com/3.0/batches/9658d3d2bd', 'method': 'GET', 'targetSchema': 'https://us12.api.mailchimp.com/schema/3.0/Definitions/Batches/Response.json'}, {'rel': 'delete', 'href': 'https://us12.api.mailchimp.com/3.0/batches/9658d3d2bd', 'method': 'DELETE'}]}
INFO:root:So far processed 2000 rows
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/src/mcwriter/writer.py", line 348, in run
    run_writer(client, params, tables, datadir=datadir)
  File "/src/mcwriter/writer.py", line 410, in run_writer
    created_lists=created_lists)
  File "/src/mcwriter/writer.py", line 318, in add_members_to_lists
    batch_action=_add_members_in_batch)
  File "/src/mcwriter/writer.py", line 291, in _do_members_action_and_wait_for_batch
    batch_response = batch_action(client, serialized_data)
  File "/src/mcwriter/writer.py", line 219, in _add_members_in_batch
    err_resp = exc.response.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
</pre>
</details>

**Comment by pocin** [comment]
my bad, I will not try to convert failed responses into jsons but raw strings instead, will fix asap

**Comment by kacurez** [comment]
ok thanks, actually it happens only sometimes, hence not a critical bug.

**Comment by pocin** [comment]
fixed in `tag 0.5.6` (already deployed in keboola so should be ready in couple minutes)
